# Generated by Django 5.1 on 2024-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=100, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
