# Generated by Django 5.1 on 2024-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SIGNMASTER", "0002_signlanguage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nickname"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                ("score", models.IntegerField(default=0, verbose_name="Score")),
            ],
        ),
        migrations.DeleteModel(
            name="SignLanguage",
        ),
    ]
